import { InternationalDisplayPolicy } from '@prisma/client'

export type CountryGatewayRuleSeed = {
  countryCode: string
  countryName: string
  regionCode: string
  regionName: string
  defaultCurrency: string
  localGatewaysEnabled: boolean
  internationalGatewaysEnabled: boolean
  internationalDisplayPolicy: InternationalDisplayPolicy
  fallbackToInternationalWhenNoLocal: boolean
  isActive: boolean
  notes: string
}

const DEF: Omit<CountryGatewayRuleSeed, 'countryCode' | 'countryName' | 'regionCode' | 'regionName' | 'defaultCurrency'> = {
  localGatewaysEnabled: false,
  internationalGatewaysEnabled: true,
  internationalDisplayPolicy: 'SHOW_FIRST',
  fallbackToInternationalWhenNoLocal: true,
  isActive: true,
  notes: 'No local gateway integrated yet; use international fallback.'
}

type Overrides = Partial<Omit<CountryGatewayRuleSeed, 'countryCode' | 'countryName' | 'regionCode' | 'regionName' | 'defaultCurrency'>>

const r = (
  cc: string,
  name: string,
  region: string,
  regionName: string,
  currency: string,
  overrides: Overrides = {}
): CountryGatewayRuleSeed => ({
  countryCode: cc,
  countryName: name,
  regionCode: region,
  regionName,
  defaultCurrency: currency,
  ...DEF,
  ...overrides
})

export const COUNTRY_GATEWAY_RULES_SEED: CountryGatewayRuleSeed[] = [
  // ── SOUTH ASIA ────────────────────────────────────────────────────────────────
  r('AF', 'Afghanistan', 'SOUTH_ASIA', 'South Asia', 'AFN'),
  r('BD', 'Bangladesh', 'SOUTH_ASIA', 'South Asia', 'BDT', {
    localGatewaysEnabled: true,
    internationalDisplayPolicy: 'HIDE_WHEN_LOCAL_EXISTS',
    fallbackToInternationalWhenNoLocal: false,
    notes: 'bKash, Nagad, SSLCommerz, EPS are preferred local gateways.'
  }),
  r('BT', 'Bhutan', 'SOUTH_ASIA', 'South Asia', 'BTN'),
  r('IN', 'India', 'SOUTH_ASIA', 'South Asia', 'INR', {
    localGatewaysEnabled: true,
    internationalDisplayPolicy: 'SHOW_AFTER_LOCAL',
    notes: 'Razorpay, Cashfree are preferred. Show international after local.'
  }),
  r('LK', 'Sri Lanka', 'SOUTH_ASIA', 'South Asia', 'LKR'),
  r('MV', 'Maldives', 'SOUTH_ASIA', 'South Asia', 'MVR'),
  r('NP', 'Nepal', 'SOUTH_ASIA', 'South Asia', 'NPR'),
  r('PK', 'Pakistan', 'SOUTH_ASIA', 'South Asia', 'PKR'),

  // ── SOUTHEAST ASIA ────────────────────────────────────────────────────────────
  r('BN', 'Brunei Darussalam', 'SOUTHEAST_ASIA', 'Southeast Asia', 'BND'),
  r('ID', 'Indonesia', 'SOUTHEAST_ASIA', 'Southeast Asia', 'IDR'),
  r('KH', 'Cambodia', 'SOUTHEAST_ASIA', 'Southeast Asia', 'KHR'),
  r('LA', 'Lao PDR', 'SOUTHEAST_ASIA', 'Southeast Asia', 'LAK'),
  r('MM', 'Myanmar', 'SOUTHEAST_ASIA', 'Southeast Asia', 'MMK'),
  r('MY', 'Malaysia', 'SOUTHEAST_ASIA', 'Southeast Asia', 'MYR'),
  r('PH', 'Philippines', 'SOUTHEAST_ASIA', 'Southeast Asia', 'PHP'),
  r('SG', 'Singapore', 'SOUTHEAST_ASIA', 'Southeast Asia', 'SGD'),
  r('TH', 'Thailand', 'SOUTHEAST_ASIA', 'Southeast Asia', 'THB'),
  r('TL', 'Timor-Leste', 'SOUTHEAST_ASIA', 'Southeast Asia', 'USD'),
  r('VN', 'Vietnam', 'SOUTHEAST_ASIA', 'Southeast Asia', 'VND'),

  // ── EAST ASIA ─────────────────────────────────────────────────────────────────
  r('CN', 'China', 'EAST_ASIA', 'East Asia', 'CNY'),
  r('HK', 'Hong Kong', 'EAST_ASIA', 'East Asia', 'HKD'),
  r('JP', 'Japan', 'EAST_ASIA', 'East Asia', 'JPY'),
  r('KP', 'North Korea', 'EAST_ASIA', 'East Asia', 'KPW'),
  r('KR', 'South Korea', 'EAST_ASIA', 'East Asia', 'KRW'),
  r('MN', 'Mongolia', 'EAST_ASIA', 'East Asia', 'MNT'),
  r('MO', 'Macao', 'EAST_ASIA', 'East Asia', 'MOP'),
  r('TW', 'Taiwan', 'EAST_ASIA', 'East Asia', 'TWD'),

  // ── CENTRAL ASIA ──────────────────────────────────────────────────────────────
  r('AM', 'Armenia', 'CENTRAL_ASIA', 'Central Asia', 'AMD'),
  r('AZ', 'Azerbaijan', 'CENTRAL_ASIA', 'Central Asia', 'AZN'),
  r('GE', 'Georgia', 'CENTRAL_ASIA', 'Central Asia', 'GEL'),
  r('KG', 'Kyrgyzstan', 'CENTRAL_ASIA', 'Central Asia', 'KGS'),
  r('KZ', 'Kazakhstan', 'CENTRAL_ASIA', 'Central Asia', 'KZT'),
  r('TJ', 'Tajikistan', 'CENTRAL_ASIA', 'Central Asia', 'TJS'),
  r('TM', 'Turkmenistan', 'CENTRAL_ASIA', 'Central Asia', 'TMT'),
  r('UZ', 'Uzbekistan', 'CENTRAL_ASIA', 'Central Asia', 'UZS'),

  // ── MENA ──────────────────────────────────────────────────────────────────────
  r('AE', 'United Arab Emirates', 'MENA', 'Middle East & North Africa', 'AED'),
  r('BH', 'Bahrain', 'MENA', 'Middle East & North Africa', 'BHD'),
  r('DZ', 'Algeria', 'MENA', 'Middle East & North Africa', 'DZD'),
  r('EG', 'Egypt', 'MENA', 'Middle East & North Africa', 'EGP'),
  r('EH', 'Western Sahara', 'MENA', 'Middle East & North Africa', 'MAD'),
  r('IL', 'Israel', 'MENA', 'Middle East & North Africa', 'ILS'),
  r('IQ', 'Iraq', 'MENA', 'Middle East & North Africa', 'IQD'),
  r('IR', 'Iran', 'MENA', 'Middle East & North Africa', 'IRR'),
  r('JO', 'Jordan', 'MENA', 'Middle East & North Africa', 'JOD', {
    localGatewaysEnabled: false,
    internationalDisplayPolicy: 'SHOW_FIRST',
    notes: 'No local gateways integrated; international only.'
  }),
  r('KW', 'Kuwait', 'MENA', 'Middle East & North Africa', 'KWD'),
  r('LB', 'Lebanon', 'MENA', 'Middle East & North Africa', 'LBP'),
  r('LY', 'Libya', 'MENA', 'Middle East & North Africa', 'LYD'),
  r('MA', 'Morocco', 'MENA', 'Middle East & North Africa', 'MAD'),
  r('MR', 'Mauritania', 'MENA', 'Middle East & North Africa', 'MRU'),
  r('OM', 'Oman', 'MENA', 'Middle East & North Africa', 'OMR'),
  r('PS', 'Palestine', 'MENA', 'Middle East & North Africa', 'ILS'),
  r('QA', 'Qatar', 'MENA', 'Middle East & North Africa', 'QAR'),
  r('SA', 'Saudi Arabia', 'MENA', 'Middle East & North Africa', 'SAR'),
  r('SD', 'Sudan', 'MENA', 'Middle East & North Africa', 'SDG'),
  r('SY', 'Syria', 'MENA', 'Middle East & North Africa', 'SYP'),
  r('TN', 'Tunisia', 'MENA', 'Middle East & North Africa', 'TND'),
  r('TR', 'Turkey', 'MENA', 'Middle East & North Africa', 'TRY'),
  r('YE', 'Yemen', 'MENA', 'Middle East & North Africa', 'YER'),

  // ── EUROPE ────────────────────────────────────────────────────────────────────
  r('AD', 'Andorra', 'EUROPE', 'Europe', 'EUR'),
  r('AL', 'Albania', 'EUROPE', 'Europe', 'ALL'),
  r('AT', 'Austria', 'EUROPE', 'Europe', 'EUR'),
  r('AX', 'Åland Islands', 'EUROPE', 'Europe', 'EUR'),
  r('BA', 'Bosnia and Herzegovina', 'EUROPE', 'Europe', 'BAM'),
  r('BE', 'Belgium', 'EUROPE', 'Europe', 'EUR'),
  r('BG', 'Bulgaria', 'EUROPE', 'Europe', 'BGN'),
  r('BY', 'Belarus', 'EUROPE', 'Europe', 'BYN'),
  r('CH', 'Switzerland', 'EUROPE', 'Europe', 'CHF'),
  r('CY', 'Cyprus', 'EUROPE', 'Europe', 'EUR'),
  r('CZ', 'Czechia', 'EUROPE', 'Europe', 'CZK'),
  r('DE', 'Germany', 'EUROPE', 'Europe', 'EUR'),
  r('DK', 'Denmark', 'EUROPE', 'Europe', 'DKK'),
  r('EE', 'Estonia', 'EUROPE', 'Europe', 'EUR'),
  r('ES', 'Spain', 'EUROPE', 'Europe', 'EUR'),
  r('FI', 'Finland', 'EUROPE', 'Europe', 'EUR'),
  r('FO', 'Faroe Islands', 'EUROPE', 'Europe', 'DKK'),
  r('FR', 'France', 'EUROPE', 'Europe', 'EUR'),
  r('GB', 'United Kingdom', 'EUROPE', 'Europe', 'GBP'),
  r('GG', 'Guernsey', 'EUROPE', 'Europe', 'GBP'),
  r('GI', 'Gibraltar', 'EUROPE', 'Europe', 'GIP'),
  r('GR', 'Greece', 'EUROPE', 'Europe', 'EUR'),
  r('HR', 'Croatia', 'EUROPE', 'Europe', 'EUR'),
  r('HU', 'Hungary', 'EUROPE', 'Europe', 'HUF'),
  r('IE', 'Ireland', 'EUROPE', 'Europe', 'EUR'),
  r('IM', 'Isle of Man', 'EUROPE', 'Europe', 'GBP'),
  r('IS', 'Iceland', 'EUROPE', 'Europe', 'ISK'),
  r('IT', 'Italy', 'EUROPE', 'Europe', 'EUR'),
  r('JE', 'Jersey', 'EUROPE', 'Europe', 'GBP'),
  r('LI', 'Liechtenstein', 'EUROPE', 'Europe', 'CHF'),
  r('LT', 'Lithuania', 'EUROPE', 'Europe', 'EUR'),
  r('LU', 'Luxembourg', 'EUROPE', 'Europe', 'EUR'),
  r('LV', 'Latvia', 'EUROPE', 'Europe', 'EUR'),
  r('MC', 'Monaco', 'EUROPE', 'Europe', 'EUR'),
  r('MD', 'Moldova', 'EUROPE', 'Europe', 'MDL'),
  r('ME', 'Montenegro', 'EUROPE', 'Europe', 'EUR'),
  r('MK', 'North Macedonia', 'EUROPE', 'Europe', 'MKD'),
  r('MT', 'Malta', 'EUROPE', 'Europe', 'EUR'),
  r('NL', 'Netherlands', 'EUROPE', 'Europe', 'EUR'),
  r('NO', 'Norway', 'EUROPE', 'Europe', 'NOK'),
  r('PL', 'Poland', 'EUROPE', 'Europe', 'PLN'),
  r('PT', 'Portugal', 'EUROPE', 'Europe', 'EUR'),
  r('RO', 'Romania', 'EUROPE', 'Europe', 'RON'),
  r('RS', 'Serbia', 'EUROPE', 'Europe', 'RSD'),
  r('RU', 'Russia', 'EUROPE', 'Europe', 'RUB'),
  r('SE', 'Sweden', 'EUROPE', 'Europe', 'SEK'),
  r('SI', 'Slovenia', 'EUROPE', 'Europe', 'EUR'),
  r('SJ', 'Svalbard and Jan Mayen', 'EUROPE', 'Europe', 'NOK'),
  r('SK', 'Slovakia', 'EUROPE', 'Europe', 'EUR'),
  r('SM', 'San Marino', 'EUROPE', 'Europe', 'EUR'),
  r('UA', 'Ukraine', 'EUROPE', 'Europe', 'UAH'),
  r('VA', 'Vatican City', 'EUROPE', 'Europe', 'EUR'),
  r('XK', 'Kosovo', 'EUROPE', 'Europe', 'EUR'),

  // ── NORTH AMERICA ─────────────────────────────────────────────────────────────
  r('BM', 'Bermuda', 'NORTH_AMERICA', 'North America', 'BMD'),
  r('CA', 'Canada', 'NORTH_AMERICA', 'North America', 'CAD', {
    localGatewaysEnabled: true,
    internationalDisplayPolicy: 'SHOW_AFTER_LOCAL',
    notes: 'Show international gateways after local ones.'
  }),
  r('GL', 'Greenland', 'NORTH_AMERICA', 'North America', 'DKK'),
  r('MX', 'Mexico', 'NORTH_AMERICA', 'North America', 'MXN'),
  r('PM', 'Saint Pierre and Miquelon', 'NORTH_AMERICA', 'North America', 'EUR'),
  r('US', 'United States', 'NORTH_AMERICA', 'North America', 'USD', {
    localGatewaysEnabled: true,
    internationalDisplayPolicy: 'SHOW_AFTER_LOCAL',
    notes: 'Stripe, Authorize.net, PayPal are preferred. Show international after local.'
  }),

  // ── LATIN AMERICA ─────────────────────────────────────────────────────────────
  r('AR', 'Argentina', 'LATIN_AMERICA', 'Latin America', 'ARS'),
  r('BO', 'Bolivia', 'LATIN_AMERICA', 'Latin America', 'BOB'),
  r('BR', 'Brazil', 'LATIN_AMERICA', 'Latin America', 'BRL'),
  r('BZ', 'Belize', 'LATIN_AMERICA', 'Latin America', 'BZD'),
  r('CL', 'Chile', 'LATIN_AMERICA', 'Latin America', 'CLP'),
  r('CO', 'Colombia', 'LATIN_AMERICA', 'Latin America', 'COP'),
  r('CR', 'Costa Rica', 'LATIN_AMERICA', 'Latin America', 'CRC'),
  r('CU', 'Cuba', 'LATIN_AMERICA', 'Latin America', 'CUP'),
  r('DO', 'Dominican Republic', 'LATIN_AMERICA', 'Latin America', 'DOP'),
  r('EC', 'Ecuador', 'LATIN_AMERICA', 'Latin America', 'USD'),
  r('GF', 'French Guiana', 'LATIN_AMERICA', 'Latin America', 'EUR'),
  r('GT', 'Guatemala', 'LATIN_AMERICA', 'Latin America', 'GTQ'),
  r('GY', 'Guyana', 'LATIN_AMERICA', 'Latin America', 'GYD'),
  r('HN', 'Honduras', 'LATIN_AMERICA', 'Latin America', 'HNL'),
  r('HT', 'Haiti', 'LATIN_AMERICA', 'Latin America', 'HTG'),
  r('NI', 'Nicaragua', 'LATIN_AMERICA', 'Latin America', 'NIO'),
  r('PA', 'Panama', 'LATIN_AMERICA', 'Latin America', 'PAB'),
  r('PE', 'Peru', 'LATIN_AMERICA', 'Latin America', 'PEN'),
  r('PY', 'Paraguay', 'LATIN_AMERICA', 'Latin America', 'PYG'),
  r('SR', 'Suriname', 'LATIN_AMERICA', 'Latin America', 'SRD'),
  r('SV', 'El Salvador', 'LATIN_AMERICA', 'Latin America', 'USD'),
  r('TT', 'Trinidad and Tobago', 'LATIN_AMERICA', 'Latin America', 'TTD'),
  r('UY', 'Uruguay', 'LATIN_AMERICA', 'Latin America', 'UYU'),
  r('VE', 'Venezuela', 'LATIN_AMERICA', 'Latin America', 'VES'),

  // ── CARIBBEAN ─────────────────────────────────────────────────────────────────
  r('AG', 'Antigua and Barbuda', 'CARIBBEAN', 'Caribbean', 'XCD'),
  r('AI', 'Anguilla', 'CARIBBEAN', 'Caribbean', 'XCD'),
  r('AW', 'Aruba', 'CARIBBEAN', 'Caribbean', 'AWG'),
  r('BB', 'Barbados', 'CARIBBEAN', 'Caribbean', 'BBD'),
  r('BL', 'Saint Barthélemy', 'CARIBBEAN', 'Caribbean', 'EUR'),
  r('BS', 'Bahamas', 'CARIBBEAN', 'Caribbean', 'BSD'),
  r('CW', 'Curaçao', 'CARIBBEAN', 'Caribbean', 'ANG'),
  r('DM', 'Dominica', 'CARIBBEAN', 'Caribbean', 'XCD'),
  r('GD', 'Grenada', 'CARIBBEAN', 'Caribbean', 'XCD'),
  r('GP', 'Guadeloupe', 'CARIBBEAN', 'Caribbean', 'EUR'),
  r('JM', 'Jamaica', 'CARIBBEAN', 'Caribbean', 'JMD'),
  r('KN', 'Saint Kitts and Nevis', 'CARIBBEAN', 'Caribbean', 'XCD'),
  r('KY', 'Cayman Islands', 'CARIBBEAN', 'Caribbean', 'KYD'),
  r('LC', 'Saint Lucia', 'CARIBBEAN', 'Caribbean', 'XCD'),
  r('MF', 'Saint Martin', 'CARIBBEAN', 'Caribbean', 'EUR'),
  r('MQ', 'Martinique', 'CARIBBEAN', 'Caribbean', 'EUR'),
  r('MS', 'Montserrat', 'CARIBBEAN', 'Caribbean', 'XCD'),
  r('PR', 'Puerto Rico', 'CARIBBEAN', 'Caribbean', 'USD'),
  r('SX', 'Sint Maarten', 'CARIBBEAN', 'Caribbean', 'ANG'),
  r('TC', 'Turks and Caicos Islands', 'CARIBBEAN', 'Caribbean', 'USD'),
  r('VC', 'Saint Vincent and the Grenadines', 'CARIBBEAN', 'Caribbean', 'XCD'),
  r('VG', 'British Virgin Islands', 'CARIBBEAN', 'Caribbean', 'USD'),
  r('VI', 'United States Virgin Islands', 'CARIBBEAN', 'Caribbean', 'USD'),

  // ── SUB-SAHARAN AFRICA ────────────────────────────────────────────────────────
  r('AO', 'Angola', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'AOA'),
  r('BF', 'Burkina Faso', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XOF'),
  r('BI', 'Burundi', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'BIF'),
  r('BJ', 'Benin', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XOF'),
  r('BW', 'Botswana', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'BWP'),
  r('CD', 'DR Congo', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'CDF'),
  r('CF', 'Central African Republic', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XAF'),
  r('CG', 'Congo', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XAF'),
  r('CI', "Côte d'Ivoire", 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XOF'),
  r('CM', 'Cameroon', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XAF'),
  r('CV', 'Cape Verde', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'CVE'),
  r('DJ', 'Djibouti', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'DJF'),
  r('ER', 'Eritrea', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'ERN'),
  r('ET', 'Ethiopia', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'ETB'),
  r('GA', 'Gabon', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XAF'),
  r('GH', 'Ghana', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'GHS'),
  r('GM', 'Gambia', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'GMD'),
  r('GN', 'Guinea', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'GNF'),
  r('GQ', 'Equatorial Guinea', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XAF'),
  r('GW', 'Guinea-Bissau', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XOF'),
  r('KE', 'Kenya', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'KES'),
  r('KM', 'Comoros', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'KMF'),
  r('LR', 'Liberia', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'LRD'),
  r('LS', 'Lesotho', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'LSL'),
  r('MG', 'Madagascar', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'MGA'),
  r('ML', 'Mali', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XOF'),
  r('MU', 'Mauritius', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'MUR'),
  r('MW', 'Malawi', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'MWK'),
  r('MZ', 'Mozambique', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'MZN'),
  r('NA', 'Namibia', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'NAD'),
  r('NE', 'Niger', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XOF'),
  r('NG', 'Nigeria', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'NGN'),
  r('RW', 'Rwanda', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'RWF'),
  r('SC', 'Seychelles', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'SCR'),
  r('SL', 'Sierra Leone', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'SLL'),
  r('SN', 'Senegal', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XOF'),
  r('SO', 'Somalia', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'SOS'),
  r('SS', 'South Sudan', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'SSP'),
  r('ST', 'São Tomé and Príncipe', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'STN'),
  r('SZ', 'Eswatini', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'SZL'),
  r('TD', 'Chad', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XAF'),
  r('TG', 'Togo', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'XOF'),
  r('TZ', 'Tanzania', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'TZS'),
  r('UG', 'Uganda', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'UGX'),
  r('ZA', 'South Africa', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'ZAR'),
  r('ZM', 'Zambia', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'ZMW'),
  r('ZW', 'Zimbabwe', 'SUB_SAHARAN_AFRICA', 'Sub-Saharan Africa', 'ZWL'),

  // ── OCEANIA ───────────────────────────────────────────────────────────────────
  r('AS', 'American Samoa', 'OCEANIA', 'Oceania', 'USD'),
  r('AU', 'Australia', 'OCEANIA', 'Oceania', 'AUD'),
  r('CC', 'Cocos (Keeling) Islands', 'OCEANIA', 'Oceania', 'AUD'),
  r('CK', 'Cook Islands', 'OCEANIA', 'Oceania', 'NZD'),
  r('CX', 'Christmas Island', 'OCEANIA', 'Oceania', 'AUD'),
  r('FJ', 'Fiji', 'OCEANIA', 'Oceania', 'FJD'),
  r('FM', 'Micronesia', 'OCEANIA', 'Oceania', 'USD'),
  r('GU', 'Guam', 'OCEANIA', 'Oceania', 'USD'),
  r('HM', 'Heard Island and McDonald Islands', 'OCEANIA', 'Oceania', 'AUD'),
  r('KI', 'Kiribati', 'OCEANIA', 'Oceania', 'AUD'),
  r('MH', 'Marshall Islands', 'OCEANIA', 'Oceania', 'USD'),
  r('MP', 'Northern Mariana Islands', 'OCEANIA', 'Oceania', 'USD'),
  r('NC', 'New Caledonia', 'OCEANIA', 'Oceania', 'XPF'),
  r('NF', 'Norfolk Island', 'OCEANIA', 'Oceania', 'AUD'),
  r('NR', 'Nauru', 'OCEANIA', 'Oceania', 'AUD'),
  r('NU', 'Niue', 'OCEANIA', 'Oceania', 'NZD'),
  r('NZ', 'New Zealand', 'OCEANIA', 'Oceania', 'NZD'),
  r('PF', 'French Polynesia', 'OCEANIA', 'Oceania', 'XPF'),
  r('PG', 'Papua New Guinea', 'OCEANIA', 'Oceania', 'PGK'),
  r('PN', 'Pitcairn', 'OCEANIA', 'Oceania', 'NZD'),
  r('PW', 'Palau', 'OCEANIA', 'Oceania', 'USD'),
  r('SB', 'Solomon Islands', 'OCEANIA', 'Oceania', 'SBD'),
  r('TK', 'Tokelau', 'OCEANIA', 'Oceania', 'NZD'),
  r('TO', 'Tonga', 'OCEANIA', 'Oceania', 'TOP'),
  r('TV', 'Tuvalu', 'OCEANIA', 'Oceania', 'AUD'),
  r('VU', 'Vanuatu', 'OCEANIA', 'Oceania', 'VUV'),
  r('WF', 'Wallis and Futuna', 'OCEANIA', 'Oceania', 'XPF'),
  r('WS', 'Samoa', 'OCEANIA', 'Oceania', 'WST'),

  // ── GLOBAL OTHER ──────────────────────────────────────────────────────────────
  r('AQ', 'Antarctica', 'GLOBAL_OTHER', 'Global / Other', 'USD'),
  r('BV', 'Bouvet Island', 'GLOBAL_OTHER', 'Global / Other', 'NOK'),
  r('FK', 'Falkland Islands', 'GLOBAL_OTHER', 'Global / Other', 'FKP'),
  r('GS', 'South Georgia and the South Sandwich Islands', 'GLOBAL_OTHER', 'Global / Other', 'GBP'),
  r('IO', 'British Indian Ocean Territory', 'GLOBAL_OTHER', 'Global / Other', 'USD'),
  r('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'GLOBAL_OTHER', 'Global / Other', 'SHP'),
  r('TF', 'French Southern Territories', 'GLOBAL_OTHER', 'Global / Other', 'EUR'),
  r('UM', 'United States Minor Outlying Islands', 'GLOBAL_OTHER', 'Global / Other', 'USD'),
]
